#!/bin/bash


if [ ! -d "$ANDROID_NDK_HOME" ]; then
  echo "The variable ANDROID_NDK_HOME does not point to valid location"
  exit
fi

#ANDROID_NDK_HOME

cd jni
so_file=$($ANDROID_NDK_HOME/ndk-build APPLICATION_MK=$(pwd)/Application.mk | grep -o -e '\S*\/libcalendars.so')
echo "lib created on path: $so_file..."

cd ..
mkdir -p calendar/src/main/jniLibs/
cp $so_file calendar/src/main/jniLibs
echo "Copying $so_file to calendar/src/main/jniLibs..."

./gradlew makeJar

jar_file=calendar/release/calendars.jar

mkdir -p output
mkdir -p output/jniLibs
mkdir -p output/libs

cp $jar_file output/jniLibs 
cp $so_file  output/libs
